name: Continuous integration

'on':
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    permissions:
      contents: read
    uses: ./.github/workflows/quality.yml
